### ISSUE TITLE
capture_screen does not work

### ISSUE THREAD

**Issue by Vingtoft** [msanders/autopy#100]
OSX 10.12.6 Python 2.7.10

Executing the following code: 

`screen = autopy.bitmap.capture_screen()`
`screen.save('images/test.png')`

will capture and save the below image. It's easy to see that something is clearly wrong.

![test](https://user-images.githubusercontent.com/1752080/32699033-70afc334-c7af-11e7-99b2-b457413fc789.png)

This is a manual screenshot (and what I was expecting):

![screen shot](https://user-images.githubusercontent.com/1752080/32699050-b9226b80-c7af-11e7-897b-06f4bdf3e9c1.png)

Is this a bug or am I doing something wrong?

**Comment by msanders** [comment]
This is fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
