### ISSUE TITLE
Autopy not supported on Win 64-bit

### ISSUE THREAD

**Issue by vcaboara** [msanders/autopy#11]
Used the 32-bit Windows installer and received the following error when trying to import autopy.

Python 2.6.4 (r264:75708, Oct 26 2009, 07:36:50) [MSC v.1500 64 bit (AMD64)] on
win32
Type "help", "copyright", "credits" or "license" for more information.

> > > import autopy
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "c:\Python26\lib\site-packages\autopy__init__.py", line 7, in <module>
> > >     import autopy.alert
> > > ImportError: DLL load failed: %1 is not a valid Win32 application.

**Comment by Moein-Aminnaseri** [comment]
Hi @msanders ,
I'm having lots of issues installing autopy on python 3.3 on win 8.1, 64bit. I searched a lot but I couldn't find any suitable .exe installer of autopy. As I see you made a nice installer for py2.7, I wonder if you have any autopy .exe installer for py3.x. Or if you know a link for it let me know.
Special thanks
