### ISSUE TITLE
Missing TAB from keys list

### ISSUE THREAD

**Issue by avi** [msanders/autopy#12]
I hope this is quicker than forking/submitting a patch

please add TAB to the list of keys supported by autopy

keycode.h:  K_TAB = kVK_Tab
keycode.h:  K_TAB = XK_Tab
keycode.h:  K_TAB = VK_TAB
autopy-key-module.c:        PyModule_AddIntMacro(mod, K_TAB) < 0 ||

**Comment by sylecn** [comment]
FYI autopy.key.type_string() argument with a literal TAB character will work. "\t" on the other hand, just insert literal "\", "t".

`type_string("  ")`

**Comment by kaitoqueiroz** [comment]
+1

**Comment by Wykleph** [comment]
Hmm, seems that this is not working on MAC OSX.  Seems odd to have to go through hoops just to type a TAB.  Is there a working solution for this?

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
