### ISSUE TITLE
incorrect "rect"

### ISSUE THREAD

**Issue by Chronnox** [msanders/autopy#15]
Whenever I try to make a screen capture of a specific region I get a black bitmap.
It looks like rect = ((100,100),(100,200)) does not work properly.
Instead of going 100x,100y into the screen it goes backward i.e. the 100,100 is -100,-100.
But when I enter -100,-100 I get a "out of bound" error.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
