### ISSUE TITLE
"Invalid conversion" error (c++) keycode.c

### ISSUE THREAD

**Issue by slremy** [msanders/autopy#22]
Hi all, and thanks again for the time and brain power dedicated towards this project!

Now that I've pulled a more recent update, I noticed that another cast conversion warning/error exists in [keycode.c](https://github.com/msanders/autopy/blob/master/src/keycode.c#L139).
`error: invalid conversion from ‘void*’ to ‘const __CFData*’`

I believe that this should be rectified with the following.
`(CFDataRef) TISGetInputSourceProperty(currentKeyboard,`

**Comment by PowerWebsite** [comment]
Key invalid

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
