### ISSUE TITLE
Rounding errors in mouse movement (windows only)

### ISSUE THREAD

**Issue by behrisch** [msanders/autopy#28]
autopy.mouse.move does not move to the correct position on the windows platform due to rounding errors. The problem are the following lines in src/mouse.c:

 point.x *= 0xFFFF / GetSystemMetrics(SM_CXSCREEN);
 point.y *= 0xFFFF / GetSystemMetrics(SM_CYSCREEN);

because if I want to move to (2000, 10) (I have two joined screens which gives a total res of 2560x1024),
it calculates for the x-coordinate 0xFFFF/2560 = 25 and then 2000 \* 25 = 50000 while the correct result is
2000 \* 0xFFFF / 2560 = 51199. This gives as a result a x-position of 50000 \* 2560 / 0xFFF = 1953 (47 pixels off).

A workaround is to use ctypes.windll.user32.SetCursorPos(2000,10) which is not equivalent (http://stackoverflow.com/questions/3720938/win32-moving-mouse-with-setcursorpos-vs-mouse-event) but may help in some cases.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
