### ISSUE TITLE
off by 1 in bitmap finding

### ISSUE THREAD

**Issue by behrisch** [msanders/autopy#29]
The coordinates of bitmaps found are always off by one in x and y direction,
best illustrated by the following code:
ARROW = autopy.bitmap.Bitmap.open("arrows.png")  
print ARROW.find_bitmap(ARROW)
results in (1,1) instead of the expected (0,0) possibly due to
findBitmapInRectAt, which does 8ofr an unknown reason)
increment the point offset before return:
                        if (needleAtOffset(needle, haystack, pointOffset, tolerance)) {  
                                ++pointOffset.x;  
                                ++pointOffset.y;  
                                *point = pointOffset;  
                                return 0;

this has the additional side effect, that the find all bitmaps code does not work properly since it does not find identical bitmaps with the same y coordinate because it starts looking at the coordinates returned by the code above.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
