### ISSUE TITLE
type_string() only handle ascii

### ISSUE THREAD

**Issue by tshirtman** [msanders/autopy#40]
if i pass a string containing non-ascii chars (like "éèçà" and their friends) only the ascii characters are typed, seems toggleUniKey() in keypress.c converst to unsigned char, so there is no unicode support whatsoever, is it possible to find a fix for that?

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) for macOS / Windows (not sure it's possible in X11).
