### ISSUE TITLE
Support Python 3

### ISSUE THREAD

**Issue by cool-RR** [msanders/autopy#45]
I'd really love for my `autopy` scripts to be run under Python 3 instead of Python 2. If `autopy` could support Python 3, that's be great.

**Comment by blueyed** [comment]
@msanders 
Would be nice to have a released version for this.

**Comment by nalf3in** [comment]
Any easy way to install the python 3 version ? It doesn't work with easy install : Missing parantheses to print

**Comment by nalf3in** [comment]
Also tried from source but got an error : error: Unable to find vcvarsall.bat and when I tried to install Microsoft Visual C++ 2008 (x64) it has crashed so if anyone can fix it :)

**Comment by MiloszKrajewski** [comment]
Please note that there is "autopy3" package in https://github.com/Riamse/autopy3

**Comment by nalf3in** [comment]
Thanks for the quick answer. 

But I have still the same problem : In pypy the only installer available is for python 2.7 and when  I tried to install from source I stil get the Unable to find vcvarsall.bat.

**Comment by MiloszKrajewski** [comment]
You probably would need VS200x (I don't remember which one, but it is quite ancient version). I usually install TCM-GCC (http://tdm-gcc.tdragon.net/download), configure distutils to use gcc (http://stackoverflow.com/questions/3297254/how-to-use-mingws-gcc-compiler-when-installing-python-package-using-pip). If it fails, I use precompiled windows packages from Christoph Gohlke (http://www.lfd.uci.edu/~gohlke/pythonlibs/) (unfortunately server not responding at this moment, but I believe it's temporary).

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
