### ISSUE TITLE
Src files won't build - gcc: error: user32.lib: No such file or directory

### ISSUE THREAD

**Issue by jner14** [msanders/autopy#50]
I get this error when trying to build it.  I've tried it on both a Windows 7 and 8 machine.  Both 64bit. It's the same error as issue 24 https://github.com/msanders/autopy/issues/24 but I tried installing Visual Studio 2008 Express and it didn't help.
# 

gcc: error: user32.lib: No such file or directory
gcc: error: Gdi32.lib: No such file or directory
D:\Software Development\Anaconda\Scripts\dllwrap.bat....\MinGW\bin\dllwrap.exe: D:\Software Development\Anaconda\Scripts\dllwrap.bat....\MinGW\bin\gcc exited with status 1
# error: command 'dllwrap' failed with exit status 1

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) which includes binary wheel distributions.
