### ISSUE TITLE
Python crashing when using the bitmap.capture_screen() function

### ISSUE THREAD

**Issue by rasteron** [msanders/autopy#53]
When trying to use the bitmap.capture_screen() function, I'm getting this error and it crashes:

**This application has requested the runtime to terminate it in an unusual way please contact the application's support**

The screen grab still works though and it saves ok.

Setup: Win7/Python 2.5/MinGW

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy).
