### ISSUE TITLE
screen.get_color always returns 0

### ISSUE THREAD

**Issue by Bechsen** [msanders/autopy#54]
Im trying to detect the color at at special point, however trying to use screen.get_color(x,y) just returns a 0 when i was expecting a hexidecimal, is there a fix for this?

**Comment by Haimrik** [comment]
I also have the same bug. Also, when I use autopy.bitmap.capture_screen it returns a black image.
Did you find any solution?

**Comment by swisscheez** [comment]
seeing same here - any fix for this?  using a win 64 machine if that matters.

**Comment by yasinyazici** [comment]
@msanders I've the same problem.

**Comment by potpath** [comment]
For Mac OS X, this problem is solved on this fork https://github.com/staydecent/autopy.
To successfully build this fork with clang, see 5cd3349c021aeaefd66854b78ec64b7be510a483 from https://github.com/potpath/autopy.

**Comment by masterakos** [comment]
+1 got the exact same issue

**Comment by stevebasher** [comment]
+1 Still getting this issue, using El Capitain on Mac.

**Comment by georgehipp** [comment]
On Windows with autopy3 replacing _autopy3.screen.get_color()_ with _autopy3.bitmap.capture_screen().get_color_ seems to circumvent the issue in my case.
**Example:**
>>> autopy3.color.hex_to_rgb(autopy3.screen.get_color(500,500))
(0, 0, 0) - Wrong
>>> autopy3.color.hex_to_rgb(autopy3.bitmap.capture_screen().get_color(500,500))
(247, 247, 247) - Correct

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy).
