### ISSUE TITLE
asnprintf and vasnprintf have conflicting types

### ISSUE THREAD

**Issue by TheWizzz** [msanders/autopy#56]
Under Win 7 x64, using Cygwin x64 v 1.7.32, gcc 4.8.3 and python 2.7.8

One gets, while doing "pip -v install autopy"
***\* error dump start ****
gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/build=/usr/src/debug/python-2.7.8-1 -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/src/Python-2.7.8=/usr/src/debug/python-2.7.8-1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DNDEBUG=1 -DMM_LITTLE_ENDIAN -DUSE_X11 -I/usr/include/python2.7 -c src/alert.c -o build/temp.cygwin-1.7.32-x86_64-2.7/src/alert.o -Wall -Wparentheses -Winline -Wbad-function-cast -Wdisabled-optimization -Wshadow
In file included from src/alert.c:13:0:
src/snprintf.h:34:12: error: conflicting types for ‘asnprintf’
 extern int asnprintf (char **ptr, size_t str_m, const char _fmt, /_args_/ ...);
            ^
In file included from /usr/include/assert.h:9:0,
                 from src/alert.c:3:
/usr/include/stdio.h:247:8: note: previous declaration of ‘asnprintf’ was here
 char \* _EXFUN(asnprintf, (char *__restrict, size_t *__restrict, const char *__restrict, ...)
        ^
In file included from src/alert.c:13:0:
src/snprintf.h:35:12: error: conflicting types for ‘vasnprintf’
 extern int vasnprintf(char *_ptr, size_t str_m, const char _fmt, va_list ap);
            ^
In file included from /usr/include/assert.h:9:0,
                 from src/alert.c:3:
/usr/include/stdio.h:275:8: note: previous declaration of ‘vasnprintf’ was here
 char \* _EXFUN(vasnprintf, (char *, size_t *, const char *, __VALIST)
        ^
error: command 'gcc' failed with exit status 1
*_**\* error dump ends ****

Commenting-out lines 34 and 35 of src/snprintf.h seems to do the trick:
//extern int asnprintf (char *_ptr, size_t str_m, const char *fmt, /_args_/ ...);
//extern int vasnprintf(char *_ptr, size_t str_m, const char *fmt, va_list ap);

Compiling is successful afterwards. 

Perhaps there's a deeper issue that someone here might get a grasp of.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy).
