### ISSUE TITLE
how to solve it?

### ISSUE THREAD

**Issue by demanLiu** [msanders/autopy#61]
when i  imoprt autopy,then
import autopy.bitmap
ImportError: /usr/local/lib/python2.7/dist-packages/autopy/bitmap.so: undefined symbol: png_set_longjmp_fn

ldd /usr/local/lib/python2.7/dist-packages/autopy/bitmap.so
    linux-vdso.so.1 =>  (0x00007fff57ffe000)
    libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f954e7c2000)
    libz.so.1 => /usr/local/lib/libz.so.1 (0x00007f954e5a9000)
    libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f954e273000)
    libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f954e055000)
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f954dc8f000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f954d988000)
    libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f954d769000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f954d565000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f954ec14000)
    libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f954d360000)
    libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f954d15a000)

i had installed libpng

**Comment by c24b** [comment]
Same problem and also unable to solve it :(

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy).
