### ISSUE TITLE
Fails to build under Yosmite OSX-10.10.5 under the anaconda environement

### ISSUE THREAD

**Issue by mherkazandjian** [msanders/autopy#76]
running build
running build_py
running build_ext
building 'screen' extension
gcc -fno-strict-aliasing -I/progs/anaconda/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DNDEBUG=1 -DMM_LITTLE_ENDIAN -DIS_MACOSX -I/progs/anaconda/anaconda/include/python2.7 -c src/autopy-screen-module.c -o build/temp.macosx-10.5-x86_64-2.7/src/autopy-screen-module.o -Wall -Wparentheses -Winline -Wbad-function-cast -Wdisabled-optimization -Wshadow
gcc -fno-strict-aliasing -I/progs/anaconda/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DNDEBUG=1 -DMM_LITTLE_ENDIAN -DIS_MACOSX -I/progs/anaconda/anaconda/include/python2.7 -c src/screen.c -o build/temp.macosx-10.5-x86_64-2.7/src/screen.o -Wall -Wparentheses -Winline -Wbad-function-cast -Wdisabled-optimization -Wshadow
In file included from /usr/include/dispatch/dispatch.h:51:0,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:15,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CFPropertyList.h:13,
                 from /System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:55,
                 from /System/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:23,
                 from src/screen.c:5:
/usr/include/dispatch/object.h:143:15: error: expected identifier or '(' before '^' token
 typedef void (^dispatch_block_t)(void);
               ^
/usr/include/dispatch/object.h:362:3: error: unknown type name 'dispatch_block_t'
   dispatch_block_t notification_block);
   ^
In file included from /usr/include/Availability.h:153:0,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:19,
                 from src/screen.c:5:
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:262:38: error: expected ',' or '}' before '**attribute**'
   kFSEventStreamCreateFlagIgnoreSelf **OSX_AVAILABLE_STARTING(__MAC_10_6, __IPHONE_6_0) = 0x00000008,
                                      ^
/System/Library/Frameworks/CoreServices.framework/Frameworks/FSEvents.framework/Headers/FSEvents.h:414:38: error: expected ',' or '}' before '__attribute**'
   kFSEventStreamEventFlagItemCreated __OSX_AVAILABLE_STARTING(__MAC_10_7, __IPHONE_6_0) = 0x00000100,
                                      ^
error: command 'gcc' failed with exit status 1

**Comment by gurinov** [comment]
+

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) which includes binary wheel distributions.
