### ISSUE TITLE
Function takes no keyword arguments

### ISSUE THREAD

**Issue by joeltio** [msanders/autopy#78]
I have a problem where the functions:
`mouse.toggle`
`type_string`
when I input keyword arguments,
`autopy.mouse.toggle(True, button=autopy.mouse.LEFT_BUTTON)`
`autopy.key.type_string("Hello, world!", wpm=60)`
the python interpreter throws an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: toggle() takes no keyword arguments
```

or

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type_string() takes no keyword arguments
```

However this works when I do not include the `button=` and `wpm=`, so it works when I type this:
`autopy.mouse.toggle(True, autopy.mouse.LEFT_BUTTON)`
`autopy.key.type_string("Hello, world!", 60)`

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy).
