### ISSUE TITLE
Typing strings and using modifiers doesn't work on Linux / my system

### ISSUE THREAD

**Issue by bolus** [msanders/autopy#8]
(Sorry for the bad English)

Hello msanders,

first of all thanks for this library. I think it has the best API I've ever seen!
Unfortunately some essential thinks in the module "key" doesn't seem to work on my system (Ubuntu).

I've written an test script with comments in it to show you what I mean (appended after the PS).
I'm using a german keyboard layout / os, could this be a problem?

Do you see the same behavior as described in my script?
If yes: Do you think the problem is easy to fix?
I would love to use your library, sadly I don't know C, so I can't debug this myself.

Best regard,
Daniel

PS: here is the test script:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from autopy import key as k

import subprocess
import time

TAB = 65289

def main( ):
    test_typing( )
    alt_tab_test( )

def test_typing( ):
    """
    typing a string doesn't works. Some chars are ignored (key.type_string) or
    the false character is written (line 24, 25)
    """
    string = "123456789!§$%&/()=?¹²³¼½¬{[]}\ "
    p = subprocess.Popen( "gedit", shell=True )
    time.sleep( 2 )
    # bad => "123456789134567()0ß1234567890ß ":
    for char in string:
        k.tap( ord( char ) )
    # worse => "123456789":
    #k.type_string( string )

def alt_tab_test( ):
    """
    modifiers don't seem to work. But it is easy to work around.
    """
    # works:
    k.toggle( k.K_ALT, True )
    k.tap( TAB )
    k.toggle( k.K_ALT, False )
    # failed with: Segmentation fault
    k.tap( TAB, k.MOD_ALT )

if __name__ == "__main__":
    main( )
```

**Comment by PowerWebsite** [comment]
Help me
