### ISSUE TITLE
bitmap.cature_screen(rect) doesn't work properly 

### ISSUE THREAD

**Issue by DavidBarishev** [msanders/autopy#83]
This may have been discussed before but capturing the screen with a region does not quite work:
`autopy.bitmap.capture_screen(((25, 25), (100, 100)))`
![img](https://cloud.githubusercontent.com/assets/13189425/16015902/8ab3d366-31a0-11e6-860e-54d527eb4da5.png)  
The capture is like moved from its place , to behind  0,0
would be awesome if this bug would be fixed , i'm running windows 10 - 64bit , python 2.7 32 bit

**Comment by DavidBarishev** [comment]
This issue has a fix here
https://github.com/msanders/autopy/pull/79
can someone please merge it , and distribute the windows binaries?
Cheers

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
