### ISSUE TITLE
Segmentation fault when using get_color

### ISSUE THREAD

**Issue by hyperutila** [msanders/autopy#84]
Running autopy with Python 2.7.11 on Mac OS X 10.11, screen.get_color throws Segmentation fault: 11
This happens for every value I have tried passing for x and y. I saw that there were previous errors with segmentations faults in the keyboard module, which were temporarily solved by casting to long. I tried that here to no avail.

**Comment by msanders** [comment]
This should be be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
