### ISSUE TITLE
Broken on Ubuntu Yakkety 16.10+, libpng12 dependency

### ISSUE THREAD

**Issue by mixmastamyk** [msanders/autopy#90]
Hi, autopy looks broken on new Ubuntus:

```
    import autopy.bitmap
    ImportError: libpng12.so.0: cannot open shared object file: No such file or directory
```

Package appears to be removed in favor of version 16:

https://launchpad.net/ubuntu/yakkety/amd64/libpng12-0

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
