### ISSUE TITLE
autopy.key.type_string() doesn't properly type SHIFT-modified characters (i.e. ":_+{})

### ISSUE THREAD

**Issue by ryanniehaus** [msanders/autopy#94]
Just started using autopy to automate using a 3rd-party Java GUI application.
It's a nice module that pretty much does what I need it to.

It works well for my needs.  However, I have found an issue:
autopy.key.type_string() doesn't seem to properly handle characters that would normally require a SHIFT key modifier.  I fixed this by making my own "type_string" functionality by wrapping autopy.key.tap() in a for key in string: loop with a if statement to add the shift key modifier.
It'd be great if I didn't have to, or at the very least... clarify that it doesn't work that way in the documentation.

**Comment by tsnork** [comment]
I'm having the same issue and it is documented in the issues multiple times.

Could you maybe share your type_string function to mitigate the issue? Thanks.

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
