### ISSUE TITLE
Still some runtime linking of Visual Studio dlls

### ISSUE THREAD

**Issue by ryanniehaus** [msanders/autopy#95]
I'm running autopy 0.51, installed via pip.

Running in a normal python shell, I don't have a problem.  However, when I run in my company's test environment, I get this:
```
>>> import autopy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\python\python27\Lib\site-packages\autopy\__init__.py", line 9, in <module>
    import autopy.alert
ImportError: DLL load failed: The specified module could not be found
```
The only differences in this environment is a few extra modules on the sys.path and a few extra environment variables.

If I launch the normal python shell with all of the same paths/environment variables, I still don't have the problem.

I'm not sure what the difference is, but it seems like I'm hitting some branch of the code that is trying to load a dll at runtime (MSVCR90.dll, according to Process Explorer).  Running the normal python shell with process explorer is not showing the offending dll is trying to be loaded.

I'm not sure what function calls would be causing this runtime linkage, but it seems you still have some dependencies on visual studio libraries...

**Comment by msanders** [comment]
This should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) which includes binary wheel distributions.
