### ISSUE TITLE
remote operation with autopy

### ISSUE THREAD

**Issue by davesliu** [msanders/autopy#96]
I want to use autopy in a shell of a remote machine. It always pop out below errors. Can it support remote mouse & key operation with autopy?

>>> import autopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "autopy/__init__.py", line 9, in <module>
    import autopy.alert
ImportError: No module named alert
>>>

**Comment by daluu** [comment]
How exactly are you running autopy in this setup? Some details would help.

On a related note, maybe this 3rd party project might help: https://github.com/daluu/autopydriverserver

**Comment by davesliu** [comment]
I can run the auotpy in a shell on desktop of Ubuntu OS. But if I tried to use  autospy in an shell on another machine to control the mouse movement of Ubuntun OS remotely, it will fail

**Comment by daluu** [comment]
My guess then is that AutoPy needs active desktop access, which running locally (if not in barebone terminal CLI mode only, e.g. fire up a shell window in Ubuntu desktop to run AutoPy) does provide.

But obviously whenever you run remotely, that access isn't there (it's a headless, CLI/terminal only session). You could do x11 forwarding, but that would just send the remote machine's UI output/desktop to your local machine which might not be what you want. Doing it with x11 forwarding, then you'd run AutoPy locally against the forwarded UI.

One alternative you have would be to use VNC to "see" the remote Ubuntu system. And run the AutoPy script via the VNC session (i.e. local shell within VNC, not remote shell from your local machine).

There are some workarounds for that kind of thing for Windows UI automation for remote desktop protocol (RDP), but I don't know of equivalents for Linux/Ubuntu, best to go the VNC route, which works cross-platform.

Or use my AutoPyDriverServer alternative which would also work, by running a server on the remote machine and connecting to it and driving the mouse via the WebDriver API (wrapper) to AutoPy.

**Comment by davesliu** [comment]
@daluu 
Thanks a lot for your detail comments :-)
The best way for me is that running a  server on the remote system and it monitor & accepts the remote mouse command and then do related  mouse movement operations

**Comment by mondeja** [comment]
I'm having the same issue, but in local. For avoid it, I'm commenting the `import autopy.alert` statement at `__init__.py`, before compiling, [like this](https://github.com/mondeja/autopy/commit/f2d6ebf47d904382e4ab932400f57c3c23f5fe7f#diff-32009ed551fd95c9e72df1ffac9fd837).

**Comment by msanders** [comment]
I believe this is a packaging issue which should be fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.
