### ISSUE TITLE
bitmap.capture_screen() method not working

### ISSUE THREAD

**Issue by mondeja** [msanders/autopy#98]
```python
>>> from autopy.bitmap import capture_screen
>>> screen = capture_screen()
SystemError: Bad call flags in PyCFunction_Call. METH_OLDARGS is no longer supported!
```

Only happens in Python3. I think that is an error in Python bindings with C. I'm trying to resolve but I don't have great experience working with C. Somebody knows? Thanks

**Comment by mondeja** [comment]
[This change](https://github.com/mondeja/autopy/commit/28c284361adef2dd4e2586d9f0cf03fe918a845a#diff-5aa6c78a3422826927298bf51b3666fd) deletes the error, but doesn't allow to call `bitmap.capture_screen` with a rect argument. Instead shows `TypeError: capture_screen() takes no keyword arguments`. I suppose that this library is not supported yet.

**Comment by msanders** [comment]
This is fixed now in the [latest version](https://github.com/autopilot-rs/autopy) of AutoPy.

**Comment by mondeja** [comment]
Thanks!
